from __future__ import annotations

MODULE_ORDER = [
    "GOV FAST PURCHASE POSTS", "LEADS GOV", "GOV DIRECT PO", "GOV OPPORTUNITIES", "GOV BUYERS", "GOV AWARDS", "GOV INCUMBENTS", "GOV AUCTIONS", "GOV PRICE INTEL", "GOV ROUTES", "GOV SUPPLIER CAPACITY", "GOV COMPLIANCE", "GOV WATCHLIST", "GOV SOURCE HEALTH", "GOV RAW DATA AUDIT"
]
MODULE_API_NAMES = {name: name.replace(" / ", "_").replace(" ", "_").replace("-", "_") for name in MODULE_ORDER}
STATUS_FAST = ["New", "Call Now", "Quote Now", "Procurement Review", "Supplier Needed", "Waiting Buyer", "Submitted", "Won", "Lost", "No-Bid"]
STATUS_LEAD = ["New", "Review", "Bid", "No-Bid", "Watch", "Submitted", "Won", "Lost"]
COMMON_SOURCE_FIELDS = ["Source Platform", "Source Record ID", "Source URL", "Raw Payload JSON", "Notes"]
MODULE_FIELDS = {
    "GOV FAST PURCHASE POSTS": ["Fast Purchase Name", "Source Platform", "Source Record ID", "Source URL", "Buyer / Agency", "Government Level", "Jurisdiction", "State / Territory", "County / City", "Buyer Contact", "Buyer Email", "Buyer Phone", "Product Category", "Product Interest", "Product Keywords Matched", "Quantity / Volume Signal", "Estimated Value", "Purchase Path", "Purchase Urgency", "Posted Date", "Due Date", "Response Deadline", "Delivery Location", "Route / Terminal Fit", "Supplier Fit", "Compliance Needed", "Direct PO Eligible", "Purchase Card Possible", "Emergency Trigger", "Fast Purchase Score", "Margin Potential", "Sales Owner", "Procurement Owner", "Next Action", "Next Action Due", "Status", "Raw Payload JSON", "Notes"],
    "LEADS GOV": ["Gov Lead Name", "Source Platform", "Source Record ID", "Source URL", "Notice Type", "Government Level", "Jurisdiction", "Agency Name", "Buying Office", "Buyer Contact", "Buyer Email", "Buyer Phone", "Product Category", "Product Interest", "NAICS", "PSC / FSC", "NIGP", "UNSPSC", "Posted Date", "Due Date", "Award Date", "Estimated Value", "Estimated Gallons / Units", "Place of Performance", "State / Territory", "Route / Terminal Fit", "Set-Aside", "Contract Vehicle", "Direct PO Eligible", "Emergency Trigger", "Priority Score", "Bid Status", "Sales Owner", "Procurement Owner", "Next Action", "Next Action Date", "Compliance Notes", "Raw Payload JSON"],
    "GOV DIRECT PO": ["Direct PO Target Name", "Buyer / Agency", "Buyer Type", "Government Level", "Jurisdiction", "Product Fit", "Likely Purchase Need", "Estimated Recurring Value", "Contact Name", "Contact Email", "Contact Phone", "Website", "Procurement Portal", "PO Instructions", "Vendor Registration Status", "Payment Method", "Credit Card / P-Card Possible", "Net Terms Possible", "Emergency Supplier Need", "Route Fit", "Sales Script", "Next Call Date", "Owner", "Status"],
    "GOV OPPORTUNITIES": ["Opportunity Name", "Source Module", "Source Record ID", "Buyer / Agency", "Product Category", "Product Interest", "Estimated Value", "Estimated Margin", "Estimated Gallons / Units", "Contract Type", "Purchase Path", "Bid / Quote Due Date", "Expected Close Date", "Stage", "Probability", "Supplier Strategy", "Logistics Strategy", "Pricing Strategy", "Compliance Strategy", "Owner", "Next Action"],
    "GOV BUYERS": ["Buyer Name", "Government Level", "Buyer Type", "Jurisdiction", "State / Territory", "County", "City", "Agency Parent", "Buying Office", "Website", "Procurement Portal", "Contact Name", "Contact Title", "Contact Email", "Contact Phone", "Products Bought", "Historical Spend", "Last Opportunity Date", "Last Award Date", "Incumbent Vendor", "Vendor Registration Requirement", "Direct PO Potential", "Recurring Demand Potential", "Notes"],
    "GOV AWARDS": ["Award Name", "Source Platform", "Source Record ID", "Source URL", "Awarding Agency", "Recipient / Vendor", "Product Category", "Product Keywords", "NAICS", "PSC / FSC", "NIGP", "Award Amount", "Obligation Amount", "Award Date", "Period of Performance Start", "Period of Performance End", "Place of Performance", "State / Territory", "Contract Vehicle", "Award Type", "Incumbent Renewal Watch", "Secure Supplies Pursuit Strategy", "Raw Payload JSON"],
    "GOV INCUMBENTS": ["Incumbent Vendor", "Buyer / Agency", "Product Category", "Contract Number", "Award Amount", "Contract Start", "Contract End", "Renewal Window", "Source URL", "Weakness / Attack Angle", "Price Opportunity", "Service Opportunity", "Logistics Opportunity", "Secure Supplies Strategy", "Status"],
    "GOV AUCTIONS": ["Auction Asset Name", "Source Platform", "Source Record ID", "Source URL", "Asset Type", "Asset Category", "Condition", "Location", "State / Territory", "Current Bid", "Estimated Market Value", "Estimated Repair Cost", "Estimated Resale Value", "Estimated Rental Value", "Auction Close Date", "Logistics Cost", "Margin Score", "Buy / Pass Recommendation", "Owner", "Status", "Raw Payload JSON"],
    "GOV PRICE INTEL": ["Price Intel Name", "Source", "Product", "Market / Region", "State", "Terminal / Rack", "Benchmark", "Index Price", "Supplier Price", "Freight Estimate", "Delivered Price Estimate", "Margin Target", "Quote Guidance", "Effective Date", "Source URL", "Notes"],
    "GOV ROUTES": ["Route Name", "Origin", "Destination", "State / Territory", "Product", "Terminal / Supplier", "Carrier", "Equipment Type", "Delivery Mode", "Freight Estimate", "Lead Time", "Route Strength", "Existing Buyer Density", "Notes"],
    "GOV SUPPLIER CAPACITY": ["Supplier / Carrier Name", "Product Category", "Product Supplied", "Geography", "Terminal / Plant / Yard", "Capacity", "Lead Time", "Delivery Equipment", "Compliance Documents", "Insurance Status", "Emergency Availability", "Pricing Basis", "Contact", "Status"],
    "GOV COMPLIANCE": ["Compliance Item", "Related Agency / Buyer", "Product", "Requirement Type", "Document Needed", "Status", "Expiration Date", "Owner", "Source URL", "Notes"],
    "GOV WATCHLIST": ["Watchlist Name", "Buyer / Agency", "Product Category", "Current Incumbent", "Last Award Amount", "Expected Renewal Window", "Trigger Source", "Action Plan", "Owner", "Next Review Date", "Status"],
    "GOV SOURCE HEALTH": ["Source Name", "Source Type", "Source URL", "API / Portal / RSS / CSV / Email", "Free or Paid", "Credential Required", "Last Sync Time", "Last Success Time", "Records Pulled", "Records Inserted", "Records Updated", "Records Failed", "Error Message", "Status", "Owner"],
    "GOV RAW DATA AUDIT": ["Raw Record Name", "Source Platform", "Source Record ID", "Source URL", "Pulled At", "Normalized Record ID", "Target Module", "Hash", "Raw Payload JSON", "Processing Status", "Error Details"]
}
VIEWS = ["A1 Call Now", "A2 Quote Now", "Due Today", "Due This Week", "Tank + Fuel", "Diesel + DEF", "Emergency Fuel", "Aviation Fuel", "Marine Fuel", "Industrial Gas", "Propane", "Water/Wastewater", "Auctions Closing Soon", "Renewal Watch", "Supplier Needed", "No-Bid Review"]
DASHBOARDS = ["Top Fast Purchase Posts", "A1 Government Money Queue", "Due Today / Due 72 Hours", "Diesel + DEF Opportunities", "Tank Rental + Fuel Opportunities", "Emergency Generator Fuel", "Aviation Fuel", "Marine / Port Fuel", "Industrial Gas Opportunities", "Propane Route Opportunities", "Water/Wastewater Chemical Opportunities", "Auctions with Margin", "Incumbent Renewal Watch", "Direct PO Buyer Call List", "Opportunities by State / Territory", "Opportunities by Product", "Opportunities by Source", "Source Health", "Failed Syncs", "Missing Credentials"]

def field_api_name(label: str) -> str:
    return label.replace("/", " ").replace("-", " ").replace("&", "and").replace(".", "").title().replace(" ", "_")
